version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb-test
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
    depends_on:
      - mongodb

  mongodb-client:
    image: mongo
    container_name: mongodb-client
    command: sleep infinity  # Keep the container running
    depends_on:
      - mongodb

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://testuser:testpassword@mongodb:27017/bluepiemeat

    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
